import sys
try:
    from libganstruc import GANStrucDeal
except:
    print 'No lib libganstruc'

import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--xyz2hd5'  , action='store_true', help='Constructing the dataset file (*.h5) of GAN using structures file *.xyz')
parser.add_argument('--xyzpath', default=None, help='Where to store structures file *.xyz')
parser.add_argument('--hd52xyz'  , action='store_true', help='Extracting structure from *.h5 file generated by GAN and write it in *.xyz file')
opt = parser.parse_args()
#print(opt)

a = GANStrucDeal.GANStruc()
if opt.xyz2hd5:
    if opt.xyzpath is None:
        print 'If xyz2hd5 is True, You need to explicitly specify the PATH Where to store structures file *.xyz'
        sys.exit(0)
    #print opt.xyzpath
    a.write_hd5_files(opt.xyzpath)
if opt.hd52xyz:
    finput = 'struc.h5'
    a.read_hd5_files_3D(finput)
